### ISSUE TITLE
Add Header to suggestions list

### ISSUE THREAD

**Issue by baselalsayed** [signavio/react-mentions#252] opened 2018-06-25 06:44 UTC
I want to add a header to suggestion list with title 'choose a symbol' and custom style, I tried more but nothing helped, I tried to solve it with css before;s content but i faced encoding problems cause the text in arabic , can I do that ?

**Comment by jfschwarz** [comment] 2018-06-25 07:14
duplicate of #65

**Closed by jfschwarz** 2018-06-25 07:14 UTC
