### ISSUE TITLE
Change Color of Mention/Highlighter Text

### ISSUE THREAD

**Issue by robbiegprocore** [signavio/react-mentions#344] opened 2019-07-26 21:29 UTC
Hey! I simply want to change the color of the text. I have tried just about everything, but I am at the conclusion that the highlighter/mention text color ALWAYS has to match the color of the textarea/input.

**Steps to reproduce:**

1. mentionStyle:
```
{
  backgroundColor: '#F0F6Fe',
  color: 'blue'
};
```

**Expected behaviour:**

![Screen Shot 2019-07-26 at 2 27 02 PM](https://user-images.githubusercontent.com/37885748/61982414-852e7f80-afb1-11e9-8244-7b593da97bd6.png)

**Observed behaviour:**

![Screen Shot 2019-07-26 at 2 25 38 PM](https://user-images.githubusercontent.com/37885748/61982438-924b6e80-afb1-11e9-9b49-a3ecd1720d1b.png)

**Comment by jfschwarz** [comment] 2019-07-27 11:36
duplicate of #184

**Closed by jfschwarz** 2019-07-27 11:36 UTC

**Comment by rakshit1610** [comment] 2020-10-29 13:17
@jfschwarz
